sudo: required
services:
    - docker

before_install:
    - docker build -t holmestm/client-test -f ./client/Dockerfile.dev ./client

script:
    - docker run -e CI=true holmestm/client-test npm run test

after_success:
    - docker build -t holmestm/multi-client ./client
    - docker build -t holmestm/multi-nginx  ./nginx
    - docker build -t holmestm/multi-server ./server
    - docker build -t holmestm/multi-worker ./worker
    - echo "$DOCKER_TOKEN" | docker login -u "$DOCKER_ID" --password-stdin
    - docker push holmestm/multi-client
    - docker push holmestm/multi-nginx
    - docker push holmestm/multi-server
    - docker push holmestm/multi-worker

deploy:
    provider: elasticbeanstalk
    region: eu-west-2
    access_key_id: 
        secure: "$AWS_ACCESS_KEY"
    secret_access_key: 
        secure: "$AWS_SECRET_KEY"
    app: multi-docker
    env: "MultiDocker-env"
    bucket_name: "elasticbeanstalk-eu-west-2-384538104517"
    bucket_path: "multi-docker"
    on:
        branch: master
