apiVersion: cert-manager.io/v1alpha2
kind: Certificate
metadata:
  name: k8s-gravitaz-tls
spec:
  secretName: k8s-gravitaz
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
  commonName: k8s.gravitaz.co.uk
  dnsNames:
    - k8s.gravitaz.co.uk
  acme: 
    config:
      - http01:
          ingressClass: nginx
        domains:
          - k8s.gravitaz.co.uk