apiVersion: cert-manager.io/v1alppha2
kind: ClusterIssuer
metadata:
  name: letsencrypt-prod
spec:
  acme:
    server: https://acme-v02.api.letsencrypt.org/directory
    email: "letsencrypt@gravitaz.co.uk"
    privateKeySecretRef:
      name: letsencrypt-prod
    solvers:
      - http01:
        ingress:
          class: nginx